import json
from pathlib import Path

def create_notebook():
    nb = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Интерактивный селектор материалов по СП 63.13330.2018\n",
                    "\n",
                    "Настоящий блокнот предназначен для оперативного выбора и анализа расчетных и нормативных характеристик бетона и арматуры в соответствии с требованиями **СП 63.13330.2018** *«Бетонные и железобетонные конструкции. Основные положения»* (с Изменениями № 1).\n",
                    "\n",
                    "### Возможности инструмента:\n",
                    "1. **Нормативные и расчетные сопротивления** для I и II групп предельных состояний ($R_b, R_{bt}, R_{bn}, R_{btn}, R_s, R_{sc}, R_{sn}$).\n",
                    "2. **Учет коэффициентов условий работы** $\\gamma_{b1} \\dots \\gamma_{b5}$ (длительность нагрузки, вертикальное бетонирование и др.).\n",
                    "3. **Деформационные характеристики и ползучесть**: начальный $E_b$ и приведенный $E_{b,red}$ модули, коэффициент ползучести $\\varphi_{b,cr}$, предельные деформации $\\varepsilon_{b0}, \\varepsilon_{b2}, \\varepsilon_{s0}, \\varepsilon_{s2}$.\n",
                    "4. **Построение деформационных диаграмм состояния**: двухлинейные (п. 6.1.21, 6.2.14), трехлинейные (п. 6.1.20) и криволинейные (Приложение Г).\n",
                    "5. **Экспорт готового Python-кода** для интеграции в последующие расчетные блокноты."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import sys\n",
                    "from pathlib import Path\n",
                    "\n",
                    "# Обеспечиваем доступ к модулю sp63_materials\n",
                    "if '.' not in sys.path:\n",
                    "    sys.path.insert(0, '.')\n",
                    "\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import ipywidgets as widgets\n",
                    "from IPython.display import display, HTML, Markdown, clear_output\n",
                    "\n",
                    "from sp63_materials import (\n",
                    "    Concrete, Rebar, \n",
                    "    list_concrete_grades, list_rebar_grades,\n",
                    "    generate_code_snippet\n",
                    ")\n",
                    "\n",
                    "print(\"Модуль sp63_materials успешно загружен.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Интерактивный дашборд выбора материалов и параметров\n",
                    "\n",
                    "Выберите класс бетона, арматуры и условия эксплуатации. Графики деформационных диаграмм и сводная спецификация обновляются в реальном времени."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Создание элементов управления (ipywidgets)\n",
                    "w_concrete_grade = widgets.Dropdown(\n",
                    "    options=list_concrete_grades(),\n",
                    "    value='B25',\n",
                    "    description='Класс бетона:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_humidity = widgets.Dropdown(\n",
                    "    options=[('Нормальная (40 - 75 %)', '40-75%'), ('Повышенная (> 75 %)', '>75%'), ('Сухая (< 40 %)', '<40%')],\n",
                    "    value='40-75%',\n",
                    "    description='Влажность среды:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_long_term = widgets.Checkbox(\n",
                    "    value=True,\n",
                    "    description='Длительное действие нагрузки (учет gamma_b1 = 0.90 и ползучести)',\n",
                    "    style={'description_width': 'initial'},\n",
                    "    layout=widgets.Layout(width='98%')\n",
                    ")\n",
                    "\n",
                    "w_vertical_casting = widgets.Checkbox(\n",
                    "    value=False,\n",
                    "    description='Вертикальное бетонирование h > 1.5 м (gamma_b3 = 0.85 для колонн/стоек)',\n",
                    "    style={'description_width': 'initial'},\n",
                    "    layout=widgets.Layout(width='98%')\n",
                    ")\n",
                    "\n",
                    "w_rebar_grade = widgets.Dropdown(\n",
                    "    options=list_rebar_grades(),\n",
                    "    value='A500',\n",
                    "    description='Класс арматуры:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_diag_model = widgets.RadioButtons(\n",
                    "    options=[\n",
                    "        ('Двухлинейная (п. 6.1.21)', 'bilinear'),\n",
                    "        ('Трехлинейная (п. 6.1.20)', 'trilinear'),\n",
                    "        ('Криволинейная нелинейная (Приложение Г)', 'nonlinear')\n",
                    "    ],\n",
                    "    value='nonlinear',\n",
                    "    description='Модель бетона:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "out_panel = widgets.Output()\n",
                    "\n",
                    "def update_view(*args):\n",
                    "    with out_panel:\n",
                    "        clear_output(wait=True)\n",
                    "        \n",
                    "        # Инициализация объектов материалов\n",
                    "        gamma_b3_val = 0.85 if w_vertical_casting.value else 1.0\n",
                    "        concrete = Concrete(\n",
                    "            grade=w_concrete_grade.value,\n",
                    "            humidity=w_humidity.value,\n",
                    "            long_term=w_long_term.value,\n",
                    "            gamma_b3=gamma_b3_val\n",
                    "        )\n",
                    "        rebar = Rebar(\n",
                    "            grade=w_rebar_grade.value,\n",
                    "            long_term=w_long_term.value\n",
                    "        )\n",
                    "        \n",
                    "        # Построение графиков\n",
                    "        fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(16, 4.8), dpi=110)\n",
                    "        plt.subplots_adjust(wspace=0.28)\n",
                    "        \n",
                    "        # 1. Сжатие бетона\n",
                    "        eps_c, sig_c = concrete.get_diagram(model=w_diag_model.value, state='compression', n_points=120)\n",
                    "        ax1.plot(eps_c * 1000, sig_c, color='#1f77b4', lw=2.2, label=f'{concrete.grade} ({w_diag_model.value})')\n",
                    "        ax1.axhline(concrete.Rb, color='#d62728', linestyle='--', alpha=0.7, label=f'Rb = {concrete.Rb} МПа')\n",
                    "        ax1.scatter([concrete.eps_b0 * 1000], [concrete.Rb], color='#d62728', zorder=5)\n",
                    "        ax1.annotate(f'({concrete.eps_b0*1000:.2f}‰; {concrete.Rb})',\n",
                    "                     xy=(concrete.eps_b0 * 1000, concrete.Rb),\n",
                    "                     xytext=(concrete.eps_b0 * 1000 * 0.65, concrete.Rb * 0.75),\n",
                    "                     arrowprops=dict(arrowstyle='->', color='#d62728', lw=1.2),\n",
                    "                     fontsize=9, fontweight='bold', color='#d62728')\n",
                    "        ax1.set_title('Бетон при осевом сжатии', fontsize=12, fontweight='bold', pad=10)\n",
                    "        ax1.set_xlabel('Деформация укорочения $\\\\varepsilon_b$, ‰', fontsize=10)\n",
                    "        ax1.set_ylabel('Напряжение $\\\\sigma_b$, МПа', fontsize=10)\n",
                    "        ax1.grid(True, linestyle=':', alpha=0.6)\n",
                    "        ax1.legend(loc='lower right', fontsize=9)\n",
                    "        \n",
                    "        # 2. Растяжение бетона\n",
                    "        eps_t, sig_t = concrete.get_diagram(model='bilinear' if w_diag_model.value == 'bilinear' else 'trilinear', state='tension', n_points=120)\n",
                    "        ax2.plot(eps_t * 1000, sig_t, color='#2ca02c', lw=2.2, label=f'{concrete.grade} растяжение')\n",
                    "        ax2.axhline(concrete.Rbt, color='#d62728', linestyle='--', alpha=0.7, label=f'Rbt = {concrete.Rbt} МПа')\n",
                    "        ax2.scatter([concrete.eps_bt0 * 1000], [concrete.Rbt], color='#d62728', zorder=5)\n",
                    "        ax2.set_title('Бетон при осевом растяжении', fontsize=12, fontweight='bold', pad=10)\n",
                    "        ax2.set_xlabel('Деформация удлинения $\\\\varepsilon_{bt}$, ‰', fontsize=10)\n",
                    "        ax2.set_ylabel('Напряжение $\\\\sigma_{bt}$, МПа', fontsize=10)\n",
                    "        ax2.grid(True, linestyle=':', alpha=0.6)\n",
                    "        ax2.legend(loc='lower right', fontsize=9)\n",
                    "        \n",
                    "        # 3. Арматура при растяжении и сжатии\n",
                    "        eps_s, sig_s = rebar.get_diagram(state='tension', n_points=120)\n",
                    "        ax3.plot(eps_s * 1000, sig_s, color='#ff7f0e', lw=2.2, label=f'{rebar.grade} (Rs = {rebar.Rs} МПа)')\n",
                    "        ax3.axhline(rebar.Rs, color='#d62728', linestyle='--', alpha=0.6)\n",
                    "        ax3.scatter([rebar.eps_s0 * 1000], [rebar.Rs], color='#d62728', zorder=5)\n",
                    "        ax3.annotate(f'$\\varepsilon_{{s0}}={rebar.eps_s0*1000:.2f}‰$',\n",
                    "                     xy=(rebar.eps_s0 * 1000, rebar.Rs),\n",
                    "                     xytext=(rebar.eps_s0 * 1000 + 1.5, rebar.Rs * 0.75),\n",
                    "                     arrowprops=dict(arrowstyle='->', color='#d62728', lw=1.2),\n",
                    "                     fontsize=9, fontweight='bold', color='#d62728')\n",
                    "        ax3.set_title(f'Арматура {rebar.grade} (Диаграмма Прандтля)', fontsize=12, fontweight='bold', pad=10)\n",
                    "        ax3.set_xlabel('Деформация удлинения $\\\\varepsilon_s$, ‰', fontsize=10)\n",
                    "        ax3.set_ylabel('Напряжение $\\\\sigma_s$, МПа', fontsize=10)\n",
                    "        ax3.grid(True, linestyle=':', alpha=0.6)\n",
                    "        ax3.legend(loc='lower right', fontsize=9)\n",
                    "        \n",
                    "        plt.show()\n",
                    "        \n",
                    "        # Сводные таблицы характеристик\n",
                    "        display(Markdown(concrete.to_markdown()))\n",
                    "        display(Markdown(rebar.to_markdown()))\n",
                    "        \n",
                    "        # Генерация сниппета кода\n",
                    "        snippet = generate_code_snippet(concrete, rebar)\n",
                    "        display(Markdown(\"### Готовый фрагмент кода для вставки в расчетный блокнот:\"))\n",
                    "        display(Markdown(f\"```python\\n{snippet}\\n```\"))\n",
                    "\n",
                    "# Привязка событий к виджетам\n",
                    "for w in [w_concrete_grade, w_humidity, w_long_term, w_vertical_casting, w_rebar_grade, w_diag_model]:\n",
                    "    w.observe(update_view, names='value')\n",
                    "\n",
                    "# Разметка интерфейса\n",
                    "box_concrete = widgets.VBox([\n",
                    "    widgets.HTML(\"<b>Параметры бетона:</b>\"),\n",
                    "    w_concrete_grade, w_humidity, w_diag_model, w_long_term, w_vertical_casting\n",
                    "], layout=widgets.Layout(padding='10px', border='1px solid #ddd', margin='4px', border_radius='6px'))\n",
                    "\n",
                    "box_rebar = widgets.VBox([\n",
                    "    widgets.HTML(\"<b>Параметры арматуры:</b>\"),\n",
                    "    w_rebar_grade\n",
                    "], layout=widgets.Layout(padding='10px', border='1px solid #ddd', margin='4px', border_radius='6px'))\n",
                    "\n",
                    "ui_controls = widgets.HBox([box_concrete, box_rebar], layout=widgets.Layout(width='100%'))\n",
                    "display(ui_controls)\n",
                    "display(out_panel)\n",
                    "\n",
                    "# Первоначальный рендер\n",
                    "update_view()"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Пример прямого программного использования\n",
                    "\n",
                    "Ниже показано, как вы можете вызывать библиотеку `sp63_materials` напрямую в любом расчетном скрипте или функции расчета сечения без графического интерфейса:"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Пример прямого расчета несущей способности прямоугольного сечения по прочности (п. 8.1.8 СП 63)\n",
                    "c = Concrete('B25', long_term=True)\n",
                    "s = Rebar('A500')\n",
                    "\n",
                    "# Геометрия сечения (мм)\n",
                    "b = 300.0   # ширина балки, мм\n",
                    "h = 600.0   # высота балки, мм\n",
                    "a = 40.0    # защитный слой до центра арматуры, мм\n",
                    "h0 = h - a  # полезная высота, мм\n",
                    "\n",
                    "# Площадь растянутой арматуры (3 стержня d25)\n",
                    "As = 3 * (np.pi * 25**2 / 4)  # ~1472 мм2\n",
                    "\n",
                    "# 1. Высота сжатой зоны бетона x:\n",
                    "# Rs * As = Rb * b * x  =>  x = (Rs * As) / (Rb * b)\n",
                    "x = (s.Rs * As) / (c.Rb * b)\n",
                    "\n",
                    "# Граничная относительная высота сжатой зоны xi_R (п. 8.1.9):\n",
                    "eps_s_el = s.Rs / s.Es\n",
                    "xi_R = 0.8 / (1.0 + eps_s_el / 0.0035)\n",
                    "x_R = xi_R * h0\n",
                    "\n",
                    "print(f\"Высота сжатой зоны x = {x:.1f} мм (предельная x_R = {x_R:.1f} мм, x/h0 = {x/h0:.3f} <= {xi_R:.3f})\")\n",
                    "\n",
                    "# 2. Предельный изгибающий момент Mult:\n",
                    "Mult = c.Rb * b * x * (h0 - 0.5 * x) / 1e6  # кН*м\n",
                    "print(f\"Несущая способность по изгибающему моменту: Mult = {Mult:.2f} кН*м\")"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "codemirror_mode": {
                    "name": "ipython",
                    "version": 3
                },
                "file_extension": ".py",
                "mimetype": "text/x-python",
                "name": "python",
                "nbconvert_exporter": "python",
                "pygments_lexer": "ipython3",
                "version": "3.13.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    nb_path = Path("C:/Users/palex/Documents/expert/materials/material_selector.ipynb")
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, indent=2)
    print(f"Created notebook at {nb_path}")

if __name__ == '__main__':
    create_notebook()
