import json
from pathlib import Path

def create_steel_notebook():
    nb = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# Интерактивный селектор стали и соединений по СП 16.13330.2017\n",
                    "\n",
                    "Настоящий блокнот предназначен для автоматизированного выбора и анализа расчетных сопротивлений прокатной стали, болтовых соединений и деформационных диаграмм в соответствии с требованиями **СП 16.13330.2017** *«Стальные конструкции»* (с Изменениями № 1 и № 2).\n",
                    "\n",
                    "### Реализованные нормативные требования:\n",
                    "1. **Точная градация по толщинам** ($t$): для фасонного проката толщина полки $t_f$ (*табл. В.5*), для листового проката и труб (*табл. В.3*), для прокатных двутавров с параллельными гранями полок по ГОСТ Р 57837 (*табл. В.4*).\n",
                    "2. **Учет статистического контроля свойств** (*сноски к табл. В.3, В.5*): числитель ($\\gamma_m = 1{,}025$) или знаменатель ($\\gamma_m = 1{,}050$).\n",
                    "3. **Полный набор расчетных сопротивлений**: растяжение/сжатие/изгиб ($R_y$), сопротивление по пределу прочности ($R_u$), сдвиг ($R_s = 0{,}58 R_y$), смятие торцевой поверхности ($R_p$), смятие в шарнирах ($R_{lp}$).\n",
                    "4. **Коэффициенты условий работы** $\\gamma_c$ (*Таблица 1*).\n",
                    "5. **Болтовые соединения**: расчетные сопротивления срезу ($R_{bs}$), растяжению ($R_{bt}$) и несущая способность болтов по *таблице Г.5*."
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "import sys\n",
                    "from pathlib import Path\n",
                    "\n",
                    "if '.' not in sys.path:\n",
                    "    sys.path.insert(0, '.')\n",
                    "\n",
                    "import numpy as np\n",
                    "import matplotlib.pyplot as plt\n",
                    "import ipywidgets as widgets\n",
                    "from IPython.display import display, HTML, Markdown, clear_output\n",
                    "\n",
                    "from sp16_materials import (\n",
                    "    StructuralSteel, SteelBolt,\n",
                    "    list_steel_grades, generate_steel_code_snippet\n",
                    ")\n",
                    "\n",
                    "print(\"Модуль sp16_materials успешно загружен.\")"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 1. Интерактивная панель выбора стали и соединений"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Виджеты управления\n",
                    "w_profile_type = widgets.Dropdown(\n",
                    "    options=[\n",
                    "        ('Фасонный прокат (ГОСТ 27772, табл. В.5)', 'shapes'),\n",
                    "        ('Листовой и универсальный прокат (табл. В.3)', 'plates'),\n",
                    "        ('Двутавры с параллельными гранями полок (ГОСТ Р 57837, табл. В.4)', 'beams_parallel'),\n",
                    "        ('Трубы круглые и профильные (табл. В.3)', 'tubes')\n",
                    "    ],\n",
                    "    value='shapes',\n",
                    "    description='Вид проката:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_steel_grade = widgets.Dropdown(\n",
                    "    options=list_steel_grades('shapes'),\n",
                    "    value='С255',\n",
                    "    description='Марка стали:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_thickness = widgets.FloatSlider(\n",
                    "    value=12.0,\n",
                    "    min=2.0,\n",
                    "    max=80.0,\n",
                    "    step=1.0,\n",
                    "    description='Толщина t (tf), мм:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_stat_control = widgets.Checkbox(\n",
                    "    value=True,\n",
                    "    description='Статистический контроль свойств (ГОСТ 27772, числитель / gamma_m=1.025)',\n",
                    "    style={'description_width': 'initial'},\n",
                    "    layout=widgets.Layout(width='98%')\n",
                    ")\n",
                    "\n",
                    "w_gamma_c = widgets.Dropdown(\n",
                    "    options=[\n",
                    "        ('Рядовые элементы конструкций (gamma_c = 1.00)', 1.00),\n",
                    "        ('Колонны жилых и общественных зданий (gamma_c = 0.95)', 0.95),\n",
                    "        ('Балки под трибунами, залами, архивами (gamma_c = 0.90)', 0.90),\n",
                    "        ('Особые условия / стесненные деформации (gamma_c = 0.85)', 0.85)\n",
                    "    ],\n",
                    "    value=1.00,\n",
                    "    description='Условия работы:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "# Болты\n",
                    "w_bolt_grade = widgets.Dropdown(\n",
                    "    options=['5.6', '5.8', '8.8', '10.9', '12.9'],\n",
                    "    value='8.8',\n",
                    "    description='Класс болта:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "w_bolt_diameter = widgets.Dropdown(\n",
                    "    options=[12, 16, 20, 24, 27, 30, 36],\n",
                    "    value=20,\n",
                    "    description='Диаметр резьбы:',\n",
                    "    style={'description_width': '140px'},\n",
                    "    layout=widgets.Layout(width='95%')\n",
                    ")\n",
                    "\n",
                    "out_panel = widgets.Output()\n",
                    "\n",
                    "def on_profile_change(change):\n",
                    "    new_grades = list_steel_grades(w_profile_type.value)\n",
                    "    w_steel_grade.options = new_grades\n",
                    "    if 'С255' in new_grades:\n",
                    "        w_steel_grade.value = 'С255'\n",
                    "    elif 'С255Б' in new_grades:\n",
                    "        w_steel_grade.value = 'С255Б'\n",
                    "    else:\n",
                    "        w_steel_grade.value = new_grades[0]\n",
                    "\n",
                    "w_profile_type.observe(on_profile_change, names='value')\n",
                    "\n",
                    "def update_view(*args):\n",
                    "    with out_panel:\n",
                    "        clear_output(wait=True)\n",
                    "        \n",
                    "        try:\n",
                    "            steel = StructuralSteel(\n",
                    "                grade=w_steel_grade.value,\n",
                    "                profile_type=w_profile_type.value,\n",
                    "                thickness=w_thickness.value,\n",
                    "                statistical_control=w_stat_control.value,\n",
                    "                gamma_c=w_gamma_c.value\n",
                    "            )\n",
                    "        except ValueError as e:\n",
                    "            print(f\"Предупреждение: {e}\")\n",
                    "            return\n",
                    "            \n",
                    "        bolt = SteelBolt(\n",
                    "            grade=w_bolt_grade.value,\n",
                    "            diameter=w_bolt_diameter.value,\n",
                    "            gamma_b=1.0\n",
                    "        )\n",
                    "        \n",
                    "        # Графика\n",
                    "        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 4.8), dpi=110)\n",
                    "        plt.subplots_adjust(wspace=0.25)\n",
                    "        \n",
                    "        # 1. Диаграмма Прандтля стали\n",
                    "        eps_arr, sig_arr = steel.get_diagram(model='prandtl', n_points=120)\n",
                    "        ax1.plot(eps_arr * 1000, sig_arr, color='#1f77b4', lw=2.4, label=f'{steel.grade} (t={steel.thickness:.0f} мм)')\n",
                    "        ax1.axhline(steel.Ry, color='#d62728', linestyle='--', alpha=0.7, label=f'Ry = {steel.Ry} МПа')\n",
                    "        ax1.axhline(steel.Ru, color='#7f7f7f', linestyle=':', alpha=0.7, label=f'Ru = {steel.Ru} МПа')\n",
                    "        ax1.scatter([steel.eps_y * 1000], [steel.Ry], color='#d62728', zorder=5)\n",
                    "        ax1.annotate(f'Текучесть ({steel.eps_y*1000:.2f}‰; {steel.Ry} МПа)',\n",
                    "                     xy=(steel.eps_y * 1000, steel.Ry),\n",
                    "                     xytext=(steel.eps_y * 1000 + 1.5, steel.Ry * 0.75),\n",
                    "                     arrowprops=dict(arrowstyle='->', color='#d62728', lw=1.2),\n",
                    "                     fontsize=9, fontweight='bold', color='#d62728')\n",
                    "        ax1.set_title(f'Диаграмма деформирования стали {steel.grade}', fontsize=12, fontweight='bold', pad=10)\n",
                    "        ax1.set_xlabel('Относительная деформация $\\\\varepsilon$, ‰', fontsize=10)\n",
                    "        ax1.set_ylabel('Напряжение $\\\\sigma$, МПа', fontsize=10)\n",
                    "        ax1.grid(True, linestyle=':', alpha=0.6)\n",
                    "        ax1.legend(loc='lower right', fontsize=9)\n",
                    "        \n",
                    "        # 2. Несущая способность болта М по диаметрам\n",
                    "        d_list = [12, 16, 20, 24, 27, 30, 36]\n",
                    "        nbs_list = [SteelBolt(w_bolt_grade.value, d).shear_capacity(1) for d in d_list]\n",
                    "        nbt_list = [SteelBolt(w_bolt_grade.value, d).tension_capacity() or 0 for d in d_list]\n",
                    "        \n",
                    "        x = np.arange(len(d_list))\n",
                    "        width = 0.38\n",
                    "        ax2.bar(x - width/2, nbs_list, width, label='Срез Nbs (1 пл.)', color='#ff7f0e', alpha=0.85)\n",
                    "        ax2.bar(x + width/2, nbt_list, width, label='Растяжение Nbt', color='#2ca02c', alpha=0.85)\n",
                    "        ax2.set_xticks(x)\n",
                    "        ax2.set_xticklabels([f'М{d}' for d in d_list])\n",
                    "        ax2.set_title(f'Несущая способность болтов кл. {w_bolt_grade.value}, кН', fontsize=12, fontweight='bold', pad=10)\n",
                    "        ax2.set_xlabel('Диаметр болта', fontsize=10)\n",
                    "        ax2.set_ylabel('Усилие, кН', fontsize=10)\n",
                    "        ax2.grid(True, linestyle=':', alpha=0.6, axis='y')\n",
                    "        ax2.legend(loc='upper left', fontsize=9)\n",
                    "        \n",
                    "        plt.show()\n",
                    "        \n",
                    "        # Вывод Markdown\n",
                    "        display(Markdown(steel.to_markdown()))\n",
                    "        display(Markdown(bolt.to_markdown()))\n",
                    "        \n",
                    "        # Сниппет\n",
                    "        snippet = generate_steel_code_snippet(steel, bolt)\n",
                    "        display(Markdown(\"### Готовый фрагмент кода для вставки в расчетный блокнот:\"))\n",
                    "        display(Markdown(f\"```python\\n{snippet}\\n```\"))\n",
                    "\n",
                    "for w in [w_profile_type, w_steel_grade, w_thickness, w_stat_control, w_gamma_c, w_bolt_grade, w_bolt_diameter]:\n",
                    "    w.observe(update_view, names='value')\n",
                    "\n",
                    "# Разметка\n",
                    "box_steel = widgets.VBox([\n",
                    "    widgets.HTML(\"<b>Параметры прокатной стали:</b>\"),\n",
                    "    w_profile_type, w_steel_grade, w_thickness, w_stat_control, w_gamma_c\n",
                    "], layout=widgets.Layout(padding='10px', border='1px solid #ddd', margin='4px', border_radius='6px'))\n",
                    "\n",
                    "box_bolts = widgets.VBox([\n",
                    "    widgets.HTML(\"<b>Параметры болтовых соединений:</b>\"),\n",
                    "    w_bolt_grade, w_bolt_diameter\n",
                    "], layout=widgets.Layout(padding='10px', border='1px solid #ddd', margin='4px', border_radius='6px'))\n",
                    "\n",
                    "ui = widgets.HBox([box_steel, box_bolts], layout=widgets.Layout(width='100%'))\n",
                    "display(ui)\n",
                    "display(out_panel)\n"
                ]
            },
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "## 2. Пример расчетного использования в инженерных задачах\n",
                    "\n",
                    "Расчет несущей способности изгибаемой балки с проверкой фланцевого болтового соединения:"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# Пример расчета несущей способности балки из стали С255 по моменту (п. 8.2 СП 16)\n",
                    "steel_beam = StructuralSteel('С255', profile_type='shapes', thickness=14.0, gamma_c=1.0)\n",
                    "\n",
                    "# Геометрические характеристики двутавра 30Б1 (СТО АСЧМ 20-93):\n",
                    "# Wx = 472.4 см3 = 472.4e3 мм3\n",
                    "Wx = 472.4e3  # мм3\n",
                    "\n",
                    "# 1. Предельный упругий изгибающий момент:\n",
                    "M_el = Wx * steel_beam.Ry / 1e6  # кН*м\n",
                    "print(f\"Сталь {steel_beam.grade} (t={steel_beam.thickness} мм): Ry = {steel_beam.Ry} МПа\")\n",
                    "print(f\"Упругий предельный момент: M_el = {M_el:.2f} кН*м\")\n",
                    "\n",
                    "# 2. Проверка опорного узла на 4 болтах М20 кл. 8.8 на сдвиг опорной реакции Q = 120 кН:\n",
                    "bolt_conn = SteelBolt('8.8', diameter=20, gamma_b=0.9)\n",
                    "n_bolts = 4\n",
                    "Q_max = n_bolts * bolt_conn.shear_capacity(n_shear_planes=1)\n",
                    "print(f\"Несущая способность болтового узла из 4xМ20 кл. 8.8: Q_max = {Q_max:.1f} кН (запас: {Q_max / 120.0:.2f})\")"
                ]
            }
        ],
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3 (ipykernel)",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.13.0"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 5
    }

    nb_path = Path("C:/Users/palex/Documents/expert/materials/steel_selector.ipynb")
    with open(nb_path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, indent=2)
    print(f"Created notebook at {nb_path}")

if __name__ == '__main__':
    create_steel_notebook()
